curl https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.min.css -o assets/codemirror.min.css
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/fold/foldgutter.min.css -o assets/foldgutter.min.css
curl https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.min.js -o assets/codemirror.min.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/keymap/emacs.min.js -o assets/emacs.min.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/mode/simple.min.js -o assets/simple.min.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/search/search.min.js -o assets/search.min.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/search/searchcursor.min.js -o assets/searchcursor.min.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/fold/foldcode.min.js -o assets/foldcode.min.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/fold/foldgutter.min.js -o assets/foldgutter.min.js
curl https://cdn.jsdelivr.net/gh/sn-extensions/components-api/dist/dist.js -o assets/dist.js
curl https://cdn.jsdelivr.net/gh/mickael-kerjean/codemirror-orgmode/orgmode-mode.js -o assets/orgmode-mode.js
curl https://cdn.jsdelivr.net/gh/mickael-kerjean/codemirror-orgmode/orgmode-fold.js -o assets/orgmode-fold.js
